name: final
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=2.0
  - pandas=2.3
  - geopandas=1.1
  - shapely=2.0
  - matplotlib=3.9
  - seaborn=0.13
  - scipy=1.13
  - scikit-learn=1.5
  - contextily=1.7
  - jupyterlab=4.2
  - ipykernel=6.29
  - pip=25.3
  - pip:
      - mystmd
      - pytest==9.0
      - shap==0.50
      - xgboost==3.1
