name: final

channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.9
  - numpy=2.0
  - scipy=1.13
  - h5py=3.12
  - pandas=2.3
  - matplotlib=3.9
  - ipykernel=6.29
  - pytest
  - tqdm
  - nbconvert
  - warnings
  - seaborn==0.13.2
  - matplotlib==3.10.7